/**
 * Background Task types — Task Streams model.
 *
 * Philosophy: Tasks are living streams that flow autonomously.
 * Users steer via inline comments, not approval gates.
 *
 * 4) states: running → flowing → paused → done
 * No approval. No evaluate-refine. Just execute and let feedback improve next run.
 */

// ── Task Status (Simplified State Machine) ──
//
//     create
//   ──────→  [running] ←─── run now / schedule fires
//               │
//               ├── complete ──→ [flowing] ←─── (recurring: idle between runs)
//               │                   │
//               │              schedule fires → [running]
//               │                   │
//               ├── error ─────→ [flowing] (retry on next schedule)
//               │
//               ├── pause ────→ [paused] ←─── auto-pause (idle timeout)
//               │                   │
//               │              resume → [running] or [flowing]
//               │
//               └── max runs ──→ [done]
//                   or one-shot

export type TaskStatus =
    | "running"     // Currently executing right now
    | "flowing"     // Idle — waiting for next scheduled run, or one-shot just completed
    | "paused"      // User paused, or auto-paused due to inactivity
    | "done";       // One-shot completed, or recurring hit max runs

export type TaskType =
    | "one_shot"    // Runs once in background, notifies when done
    | "recurring"   // Runs on schedule (e.g., "every 2 days")
    | "continuous"  // Runs indefinitely, reacts to events (future)
    | "triggered";  // Waits for trigger, then executes (future)

// ── Task Schedule ──

export interface TaskSchedule {
    /** Human-readable interval: "2 days", "weekly", "hourly", "30 minutes" */
    interval: string;
    /** Parsed interval in milliseconds */
    intervalMs: number;
    /** Unix timestamp of next scheduled run */
    nextRunAt: number;
    /** Number of times this task has executed */
    runCount: number;
    /** Maximum number of runs (undefined = infinite) */
    maxRuns?: number;
}

// ── Task Plan ──

export interface TaskPhase {
    id: string;
    description: string;
    status: "pending" | "running" | "completed" | "failed" | "skipped";
    startedAt?: number;
    completedAt?: number;
}

export interface TaskPlan {
    phases: TaskPhase[];
    qualityCriteria: string;
    estimatedDurationMin?: number;
}

// ── Task Memory (persists across runs) ──

export interface TaskComment {
    /** The steering comment from the user */
    text: string;
    /** When the comment was posted */
    timestamp: number;
    /** Which run number incorporated this comment (set when next run starts) */
    appliedToRun?: number;
}

export interface TaskMemory {
    /** Key learnings / facts discovered across runs */
    findings: string[];
    /** URLs, files, or sources referenced */
    sources: string[];
    /** User decisions that inform future runs (legacy compat + steering) */
    decisions: string[];
    /** Output files created by this task */
    filesCreated: string[];
    /** User steering comments — replaces the old feedback/approval system */
    comments: TaskComment[];
}

// ── Auto-Pause Config ──

export interface AutoPauseConfig {
    /** Whether auto-pause is enabled for this task */
    enabled: boolean;
    /** Idle timeout in milliseconds before auto-pausing (default: 7 days) */
    idleTimeoutMs: number;
}

/** Default auto-pause: 7 days of no interaction */
export const DEFAULT_AUTO_PAUSE: AutoPauseConfig = {
    enabled: true,
    idleTimeoutMs: 7 * 24 * 60 * 60 * 1000, // 7 days
};

// ── Task Run (execution log) ──

export interface TaskRun {
    id: string;
    taskId: string;
    /** Sequential run number (1, 2, 3...) */
    runNumber: number;
    status: "running" | "completed" | "failed";
    startedAt: number;
    completedAt?: number;
    /** Duration in ms */
    durationMs?: number;
    /** Summary of what happened during this run */
    summary?: string;
    /** Phases executed during this run */
    phases: TaskPhase[];
    /** Tool calls made during this run */
    toolCalls: Array<{
        tool: string;
        input: any;
        output?: any;
        durationMs?: number;
    }>;
    /** Generated output (text, file paths, etc.) */
    output?: string;
    /** Error message if failed */
    error?: string;
    /** Quality score (heuristic, not LLM-based) */
    evaluation?: {
        satisfied: boolean;
        qualityScore: number;
        issues: string[];
    };
}

// ── Background Task (main entity) ──

export interface BackgroundTask {
    id: string;
    /** Original user intent / goal */
    goal: string;
    taskType: TaskType;
    status: TaskStatus;

    /** Execution plan (generated by reasoning engine) */
    plan: TaskPlan;

    /** Schedule config (for recurring tasks) */
    schedule?: TaskSchedule;

    /** Auto-pause configuration (per-task, user can customize) */
    autoPause: AutoPauseConfig;

    /** Persistent memory across runs */
    memory: TaskMemory;

    /** Linked conversation thread ID */
    threadId?: string;

    /** Timestamps */
    createdAt: number;
    updatedAt: number;
    lastRunAt?: number;
    /** Last time the user interacted (steered, ran now, etc.) */
    lastInteractionAt?: number;

    /** Directory for output files */
    outputDir?: string;

    /** Runs completed for this task (summary only; full runs stored separately) */
    totalRuns: number;
    successfulRuns: number;
}

// ── Task Registry (index of all tasks) ──

export interface TaskRegistryEntry {
    id: string;
    goal: string;
    taskType: TaskType;
    status: TaskStatus;
    threadId?: string;
    nextRunAt?: number;
    lastRunAt?: number;
    totalRuns: number;
    createdAt: number;
    updatedAt: number;
}

// ── Helpers ──

/** Valid transitions from each state */
export const VALID_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
    running: ["flowing", "paused", "done"],
    flowing: ["running", "paused", "done"],
    paused: ["flowing", "running", "done"],
    done: [],  // terminal state
};

/** Check if a status transition is valid */
export function canTransition(from: TaskStatus, to: TaskStatus): boolean {
    if (from === to) return true; // Self-transitions are no-ops — always valid
    return VALID_TRANSITIONS[from].includes(to);
}

/** Create an empty task memory */
export function emptyMemory(): TaskMemory {
    return {
        findings: [],
        sources: [],
        decisions: [],
        filesCreated: [],
        comments: [],
    };
}

/** Parse a human-readable interval string to milliseconds */
export function parseInterval(interval: string): number {
    const lower = interval.toLowerCase().trim();

    // Match patterns like "2 days", "30 minutes", "1 hour", "weekly"
    const match = lower.match(/^(\d+)\s*(second|minute|hour|day|week|month)s?$/);
    if (match) {
        const n = parseInt(match[1], 10);
        const unit = match[2];
        const multipliers: Record<string, number> = {
            second: 1000,
            minute: 60 * 1000,
            hour: 60 * 60 * 1000,
            day: 24 * 60 * 60 * 1000,
            week: 7 * 24 * 60 * 60 * 1000,
            month: 30 * 24 * 60 * 60 * 1000,
        };
        return n * (multipliers[unit] || 0);
    }

    // Named intervals
    const named: Record<string, number> = {
        hourly: 60 * 60 * 1000,
        daily: 24 * 60 * 60 * 1000,
        weekly: 7 * 24 * 60 * 60 * 1000,
        monthly: 30 * 24 * 60 * 60 * 1000,
    };
    if (named[lower]) return named[lower];

    // Fallback: 1 day
    console.warn(`[tasks] Could not parse interval "${interval}", defaulting to 1 day`);
    return 24 * 60 * 60 * 1000;
}
