/**
 * Artifact Types — files generated by the agent linked to conversations/tasks.
 *
 * Artifacts are outputs (articles, reports, configs, code) that the agent creates.
 * They are stored in a predictable location and linked to their source context
 * (conversation or task) so users can always find them.
 */

// ── Artifact ──

export interface Artifact {
    /** Unique artifact ID */
    id: string;
    /** Display name (e.g., "ai_article_today.md") */
    name: string;
    /** Absolute path where the artifact is stored */
    path: string;
    /** MIME type (detected from extension) */
    mimeType: string;
    /** File size in bytes */
    size: number;
    /** What created this artifact */
    contextType: "conversation" | "task";
    /** ID of the conversation or task */
    contextId: string;
    /** Timestamp when created */
    createdAt: number;
}

// ── Artifact Context ──

export interface ArtifactContext {
    /** Whether this is from a conversation or a task */
    type: "conversation" | "task";
    /** The conversation threadId or task ID */
    id: string;
    /** Active workspace path (if set, artifacts go here instead of ~/.niom) */
    workspace?: string;
}

// ── Artifact Manifest ──
// One manifest per context — stored alongside artifacts

export interface ArtifactManifest {
    contextType: "conversation" | "task";
    contextId: string;
    artifacts: Artifact[];
    updatedAt: number;
}

// ── MIME Detection ──

const EXTENSION_MIME: Record<string, string> = {
    // Text
    md: "text/markdown",
    txt: "text/plain",
    csv: "text/csv",
    // Code
    ts: "text/typescript",
    tsx: "text/typescript",
    js: "text/javascript",
    jsx: "text/javascript",
    py: "text/x-python",
    rs: "text/x-rust",
    go: "text/x-go",
    java: "text/x-java",
    // Config
    json: "application/json",
    yaml: "application/yaml",
    yml: "application/yaml",
    toml: "application/toml",
    xml: "application/xml",
    // Web
    html: "text/html",
    css: "text/css",
    svg: "image/svg+xml",
    // Data
    sql: "text/x-sql",
    sh: "text/x-shellscript",
    // Binary
    png: "image/png",
    jpg: "image/jpeg",
    gif: "image/gif",
    pdf: "application/pdf",
};

export function detectMimeType(filename: string): string {
    const ext = filename.split(".").pop()?.toLowerCase() || "";
    return EXTENSION_MIME[ext] || "application/octet-stream";
}
