/**
 * ArtifactsList — displays artifacts generated by a conversation or task.
 *
 * Features:
 *   - Compact file list with icons, names, sizes, and timestamps
 *   - Inline preview for text-based artifacts
 *   - "Open in Explorer" action (Tauri)
 *   - Reusable in TasksView and WorkspaceView
 */

import { useState, useCallback } from "react";
import { type Artifact, formatFileSize, getFileIcon } from "../hooks/useArtifacts";
import { getSidecarUrl } from "../lib/useConfig";

interface ArtifactsListProps {
    artifacts: Artifact[];
    loading?: boolean;
    compact?: boolean;
    onRefresh?: () => void;
}

export function ArtifactsList({ artifacts, loading, compact, onRefresh }: ArtifactsListProps) {
    const [previewId, setPreviewId] = useState<string | null>(null);
    const [previewContent, setPreviewContent] = useState<string | null>(null);
    const [previewLoading, setPreviewLoading] = useState(false);

    const handlePreview = useCallback(async (artifact: Artifact) => {
        if (previewId === artifact.id) {
            setPreviewId(null);
            setPreviewContent(null);
            return;
        }

        // Only preview text-based files
        if (!artifact.mimeType.startsWith("text/") &&
            artifact.mimeType !== "application/json" &&
            artifact.mimeType !== "application/yaml" &&
            artifact.mimeType !== "application/toml") {
            return;
        }

        setPreviewId(artifact.id);
        setPreviewLoading(true);
        try {
            const params = new URLSearchParams({
                contextType: artifact.contextType,
                contextId: artifact.contextId,
            });
            const res = await fetch(`${getSidecarUrl()}/artifacts/${artifact.id}/content?${params}`);
            if (!res.ok) throw new Error(`HTTP ${res.status}`);
            const data = await res.json();
            setPreviewContent(data.content || "(empty)");
        } catch {
            setPreviewContent("(failed to load preview)");
        } finally {
            setPreviewLoading(false);
        }
    }, [previewId]);

    const handleOpenInExplorer = useCallback(async (artifact: Artifact) => {
        try {
            // Use Tauri's invoke API if available (works in production Tauri app)
            if ((window as any).__TAURI_INTERNALS__) {
                const { invoke } = await import("@tauri-apps/api/core");
                // Tauri's shell open command
                await invoke("plugin:shell|open", { path: artifact.path.replace(/[/\\][^/\\]+$/, "") });
                return;
            }
        } catch { /* not in Tauri or command not available */ }

        // Fallback: copy path to clipboard
        try {
            await navigator.clipboard.writeText(artifact.path);
        } catch { /* ignore */ }
    }, []);

    if (loading) {
        return (
            <div className="text-[10px] text-text-muted py-1 px-2 animate-pulse">
                Loading artifacts...
            </div>
        );
    }

    if (artifacts.length === 0) {
        return null; // Don't show anything if no artifacts
    }

    return (
        <div className={`flex flex-col ${compact ? "gap-0.5" : "gap-1"}`}>
            {/* Header */}
            <div className="flex items-center justify-between px-1">
                <div className="text-[10px] font-medium text-text-secondary flex items-center gap-1">
                    <span>📎</span>
                    <span>Artifacts</span>
                    <span className="text-text-muted">({artifacts.length})</span>
                </div>
                {onRefresh && (
                    <button
                        onClick={onRefresh}
                        className="text-[9px] text-text-muted hover:text-accent transition-colors"
                        title="Refresh artifacts"
                    >
                        ↻
                    </button>
                )}
            </div>

            {/* Artifact entries */}
            {artifacts.map((a) => (
                <div key={a.id} className="flex flex-col">
                    <div
                        className="flex items-center gap-1.5 px-1.5 py-1 rounded-md hover:bg-white/5 cursor-pointer group transition-colors"
                        onClick={() => handlePreview(a)}
                    >
                        <span className="text-xs shrink-0">{getFileIcon(a.mimeType)}</span>
                        <div className="flex-1 min-w-0">
                            <div className="text-[10px] text-text-primary font-medium truncate">
                                {a.name}
                            </div>
                            <div className="text-[8px] text-text-muted flex items-center gap-1">
                                <span>{formatFileSize(a.size)}</span>
                                <span>·</span>
                                <span>{new Date(a.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span>
                            </div>
                        </div>
                        <button
                            onClick={(e) => { e.stopPropagation(); handleOpenInExplorer(a); }}
                            className="text-[9px] text-text-muted hover:text-accent opacity-0 group-hover:opacity-100 transition-all shrink-0"
                            title="Open in file explorer"
                        >
                            📂
                        </button>
                    </div>

                    {/* Inline preview */}
                    {previewId === a.id && (
                        <div className="mx-1.5 mt-0.5 mb-1 rounded border border-border/30 bg-black/10 overflow-hidden">
                            {previewLoading ? (
                                <div className="text-[9px] text-text-muted p-2 animate-pulse">Loading...</div>
                            ) : (
                                <pre className="font-mono text-[9px] leading-relaxed text-text-secondary p-2 max-h-[200px] overflow-y-auto whitespace-pre-wrap break-words">
                                    {previewContent}
                                </pre>
                            )}
                        </div>
                    )}
                </div>
            ))}
        </div>
    );
}
